# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_auto_20171003_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin')],
                                   default=0, max_length=10),
        ),
    ]
