# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Account', '0004_auto_20171003_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
