# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_account_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='answer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='question',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
