# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0006_auto_20171004_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='completed',
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin')],
                                   default='Student', max_length=10),
        ),
    ]
