# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0007_auto_20171004_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='telephone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
