# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0008_auto_20171016_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
