# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0010_account_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='major',
            field=models.CharField(choices=[('EE', 'EE'), ('CS', 'CS')], default='EE', max_length=10),
        ),
    ]
