# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_account_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin'), ('Blacklist', 'Blacklist')], default='Student', max_length=10),
        ),
    ]
