# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20171030_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='major',
            field=models.CharField(choices=[('EE', 'EE'), ('CS', 'CS'), ('CST', 'CST')], default='EE', max_length=10),
        ),
    ]
