# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0014_auto_20171111_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='major',
            field=models.CharField(
                choices=[('\u7535\u5b50', '\u7535\u5b50'), ('\u8ba1\u7b97\u673a', '\u8ba1\u7b97\u673a'),
                         ('\u8ba1\u7b97\u673a\u5e08\u8303', '\u8ba1\u7b97\u673a\u5e08\u8303')], default='\u7535\u5b50',
                max_length=10),
        ),
    ]
