# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-19 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0015_auto_20171111_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='major',
            field=models.CharField(max_length=10),
        ),
    ]
