# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-19 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0016_auto_20171119_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
