# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-20 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_account_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='account',
            name='question',
        ),
        migrations.AddField(
            model_name='account',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
