# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-02 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration',
                 models.CharField(choices=[(0, '0:00-1:00'), (1, '1:00-2:00')], default=False, max_length=10)),
                ('classroom',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Classroom')),
            ],
        ),
    ]
