# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-02 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Appointment', '0002_auto_20171002_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(choices=[(0, '0:00-1:00'), (1, '1:00-2:00')], max_length=10),
        ),
    ]
