# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appointment', '0003_auto_20171002_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(choices=[(0, '0:00-1:00'), (1, '1:00-2:00')]),
        ),
    ]
