# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20171003_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='classroom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='custom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(choices=[(0, '8:00-8:30'), (1, '8:30-9:00'), (2, '9:00-9:30'), (3, '9:30-10:00'), (4, '10:00-10:30'), (5, '10:30-11:00'), (6, '11:00-11:30'), (7, '11:30-12:00'), (8, '12:00-12:30'), (9, '12:30-13:00'), (10, '13:30-14:00'), (11, '14:00-14:30'), (12, '14:30-15:00'), (13, '15:00-15:30'), (14, '15:30-16:00'), (15, '16:00-16:30'), (16, '16:30-17:00'), (17, '17:30-18:00'), (18, '18:00-18:30'), (19, '18:30-19:00'), (20, '19:00-19:30'), (21, '19:30-20:00'), (22, '20:00-20:30'), (23, '20:30-21:00'), (24, '21:00-21:30'), (25, '21:30-22:00'), (26, '22:00-23:00')]),
        ),
    ]
