# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20171009_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 14, 11, 28, 247000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='classroom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='custom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(max_length=1000),
        ),
    ]
