# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_auto_20171008_1820'),
        ('appointment', '0007_auto_20171009_2211'),
    ]

    operations = [
    ]
