# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 12:42
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appointment', '0023_auto_20171018_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='desk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='multimedia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(
                choices=[(0, '\u672a\u5230\u9884\u7ea6\u65f6\u95f4'), (1, '\u67dc\u95e8\u5df2\u6253\u5f00'),
                         (2, '\u5df2\u53d6\u8d70\u94a5\u5319'), (3, '\u94a5\u5319\u5df2\u8fd8')], default=0,
                max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='custom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
