# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 16:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appointment', '0024_auto_20171020_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-date', 'start')},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='custom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.CharField(
                choices=[('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15),
                         ('16', 16), ('17', 17), ('18', 18), ('19', 19), ('20', 20), ('21', 21), ('22', 22),
                         ('23', 23)], max_length=2),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.CharField(
                choices=[('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15),
                         ('16', 16), ('17', 17), ('18', 18), ('19', 19), ('20', 20), ('21', 21), ('22', 22),
                         ('23', 23)], max_length=2),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(
                choices=[(0, '\u672a\u5230\u9884\u7ea6\u65f6\u95f4'), (1, '\u67dc\u95e8\u5df2\u6253\u5f00'),
                         (2, '\u5df2\u53d6\u8d70\u94a5\u5319'), (3, '\u94a5\u5319\u5df2\u8fd8'),
                         (4, '\u9884\u7ea6\u5df2\u53d6\u6d88')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set([('date', 'start')]),
        ),
    ]
