# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 12:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0028_auto_20171022_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='boss',
            field=models.CharField(default='xiqi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='director_phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='custom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set([('date', 'start'), ('date', 'end')]),
        ),
    ]
