# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 08:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('classroom', '0002_classroom_location'),
        ('appointment', '0035_auto_20171117_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='custom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set([('classroom', 'date', 'start', 'status'), ('classroom', 'date', 'end', 'status')]),
        ),
    ]
